# =============================================================================
# Bayesian Structural Equation Model (SEM) — revised without Fv/Fm
# Fagus sylvatica transcriptome — light gradient analysis
#
# Model structure:
#
#   Leaf position → Gene expression PC1    (developmental acclimation)
#   Lux           → Gene expression PC1    (acute light drives transcriptome)
#   Lux           → PIabs                  (light drives photosynthetic performance)
#   Gene expression PC1 → PIabs            (transcriptome mediates performance)
#
# Fv/Fm excluded due to ambiguous causal position in model
#
# Sub-models:
#   1. pc1_std    ~ mo(pos) + lux_std + (1|genotype)    Gaussian
#   2. mean_pi_abs ~ lux_std + pc1_std + (1|genotype)   Gamma, log link
#
# Tool: brms (Bayesian multilevel models via Stan)
#
# Input:  sem_data.csv  — pre-computed from the companion WGCNA pipeline
#                         (ENA: PRJEB64934; see README.md)
# =============================================================================

# -----------------------------------------------------------------------------
# 0. Libraries
# -----------------------------------------------------------------------------
library(brms)
library(dplyr)
library(ggplot2)

# -----------------------------------------------------------------------------
# 1. Load pre-computed SEM data
#    sem_data.csv is generated by the companion WGCNA pipeline.
#    Required columns:
#      pc1_std     — standardised PC1 of 15,126 leaf-position-responsive genes
#      lux_std     — standardised light intensity (lux)
#      mean_pi_abs — photosynthetic performance index (raw, strictly positive)
#      pos         — ordered factor 1–7 (shade to sun)
#      genotype    — tree identifier (random effect)
# -----------------------------------------------------------------------------
message("--- Step 1: Load pre-computed SEM data ---")

sem_data <- read.csv("sem_data.csv", row.names = 1)

# Restore factor types
sem_data$genotype <- factor(sem_data$genotype)
sem_data$pos      <- factor(sem_data$condition_num,
                             levels  = 1:7,
                             ordered = TRUE)

message("Samples: ", nrow(sem_data))
message("Variables: ", paste(names(sem_data), collapse = ", "))

# Quick sanity checks
message("\nCorrelations:")
print(round(cor(sem_data[, c("condition_num", "lux_std", "pc1_std")],
                use = "pairwise.complete.obs"), 3))
message("\nPIabs range: ",
        paste(round(range(sem_data$mean_pi_abs, na.rm = TRUE), 3),
              collapse = " to "))

# -----------------------------------------------------------------------------
# 2. Define sub-models
# -----------------------------------------------------------------------------
message("\n--- Step 2: Define sub-models ---")

# Sub-model 1: leaf position + Lux → Gene expression PC1
# Gaussian family: PC1 is standardised, can be negative, approximately normal
# Both pos and lux included: separates developmental and acute effects
bf_pc1 <- bf(
  pc1_std ~ mo(pos) + lux_std + (1 | genotype),
  family = gaussian()
)

# Sub-model 2: Lux + PC1 → PIabs
# Gamma family: PIabs is strictly positive and right-skewed
# No direct path from leaf position — positional effect fully mediated
# by Lux and PC1
bf_piabs <- bf(
  mean_pi_abs ~ lux_std + pc1_std + (1 | genotype),
  family = Gamma(link = "log")
)

message("Sub-models defined:")
message("  1. pc1_std    ~ mo(pos) + lux_std + (1|genotype)    [Gaussian]")
message("  2. mean_pi_abs ~ lux_std + pc1_std + (1|genotype)   [Gamma, log]")

# -----------------------------------------------------------------------------
# 3. Specify priors
# -----------------------------------------------------------------------------
message("\n--- Step 3: Specify priors ---")

# Weakly informative priors
# normal(0,1) for fixed effects — appropriate for standardised predictors
# gamma(2, 0.1) for shape parameters — allows high shape (tight distribution)
#   which is expected for PIabs
# Default half-Student-t(3,0,2.5) retained for random effect SDs

my_prior <- c(
  # Fixed effects — all response variables
  prior(normal(0, 1), class = "b", resp = "pc1std"),
  prior(normal(0, 1), class = "b", resp = "meanpiabs"),

  # Shape parameter for Gamma distribution
  prior(gamma(2, 0.1), class = "shape", resp = "meanpiabs")
)

message("Priors specified:")
message("  Fixed effects:  normal(0, 1)")
message("  Gamma shape:    gamma(2, 0.1)")
message("  Random effects: student_t(3, 0, 2.5) [default]")

# -----------------------------------------------------------------------------
# 4. Fit the joint Bayesian SEM
# -----------------------------------------------------------------------------
# set_rescor(FALSE) -> residual correlations between sub-models not estimated

message("\n--- Step 4: Fit Bayesian SEM ---")
message("2 sub-models × 4 chains × 5000 iterations")
message("Expected runtime: 10–20 minutes")

fit_sem <- brm(
  formula = bf_pc1 + bf_piabs + set_rescor(FALSE),
  data    = sem_data,
  prior   = my_prior,
  chains  = 4,
  cores   = 4,
  iter    = 5000,
  warmup  = 1000,
  control = list(adapt_delta = 0.95),
  seed    = 42,
  file    = "sem_bayesian_fit_no_fvfm"   # saves to disk; reloads automatically if unchanged
)

message("\nFitting complete.")

# -----------------------------------------------------------------------------
# 5. Check convergence
# -----------------------------------------------------------------------------
message("\n--- Step 5: Check convergence ---")

convergence_check <- summary(fit_sem)

# All Rhat should be < 1.01
rhats <- convergence_check$fixed$Rhat
message("Max Rhat: ", round(max(rhats, na.rm = TRUE), 4),
        " (should be < 1.01)")

# ESS should be > 400
ess_bulk <- convergence_check$fixed$Bulk_ESS
message("Min Bulk ESS: ", round(min(ess_bulk, na.rm = TRUE), 0),
        " (should be > 400)")

# Divergent transitions
n_divergent <- sum(nuts_params(fit_sem)$Value[
  nuts_params(fit_sem)$Parameter == "divergent__"
])
message("Divergent transitions: ", n_divergent,
        ifelse(n_divergent > 0,
               " — WARNING: increase adapt_delta to 0.99",
               " — OK"))

# Trace plots
pdf("sem_trace_plots_no_fvfm.pdf", width = 12, height = 8)
plot(fit_sem, ask = FALSE)
dev.off()
message("Saved: sem_trace_plots_no_fvfm.pdf")

message("\n--- Full model summary ---")
print(summary(fit_sem))

# -----------------------------------------------------------------------------
# 6. Extract path coefficients
# -----------------------------------------------------------------------------
message("\n--- Step 6: Extract path coefficients ---")

coef_table <- as.data.frame(fixef(fit_sem))
coef_table$parameter <- rownames(coef_table)

paths_of_interest <- c(
  "pc1std_mopos",        # leaf position → PC1
  "pc1std_lux_std",      # Lux → PC1
  "meanpiabs_lux_std",   # Lux → PIabs
  "meanpiabs_pc1_std"    # PC1 → PIabs
)

path_df <- coef_table %>%
  filter(parameter %in% paths_of_interest) %>%
  mutate(
    path = case_when(
      parameter == "pc1std_mopos"      ~ "Leaf position → PC1",
      parameter == "pc1std_lux_std"    ~ "Lux → PC1",
      parameter == "meanpiabs_lux_std" ~ "Lux → PIabs",
      parameter == "meanpiabs_pc1_std" ~ "PC1 → PIabs"
    ),
    credible = !(Q2.5 < 0 & Q97.5 > 0)
  ) %>%
  dplyr::select(path, Estimate, Est.Error, Q2.5, Q97.5, credible)

message("\nPath coefficients (posterior median + 95% CI):")
print(round(path_df[, -1], 3) %>% cbind(path_df[, 1], .))

#                 path_df[, 1] Estimate Est.Error   Q2.5  Q97.5 credible
# pc1std_lux_std              Lux → PC1    0.449     0.064  0.322  0.576        1
# meanpiabs_lux_std         Lux → PIabs   -0.104     0.026 -0.155 -0.053        1
# meanpiabs_pc1_std         PC1 → PIabs   -0.106     0.028 -0.162 -0.050        1
# pc1std_mopos      Leaf position → PC1    0.109     0.025  0.061  0.158        1

write.csv(path_df, "sem_path_coefficients_no_fvfm.csv",
          row.names = FALSE)
message("Saved: sem_path_coefficients_no_fvfm.csv")

# Monotonic simplex parameters
message("\nMonotonic simplex parameters:")
message("(proportion of total monotonic effect at each position transition)")
simplex <- as.data.frame(fixef(fit_sem)) %>%
  filter(grepl("mopos1", rownames(.)))
simplex$parameter <- rownames(simplex)
print(simplex[, c("parameter", "Estimate", "Q2.5", "Q97.5")] %>%
        mutate(across(where(is.numeric), round, 3)))

# -----------------------------------------------------------------------------
# 7. Bayesian R² per sub-model
# -----------------------------------------------------------------------------
message("\n--- Step 7: Bayesian R² ---")

r2_pc1   <- bayes_R2(fit_sem, resp = "pc1std")
r2_piabs <- bayes_R2(fit_sem, resp = "meanpiabs")

r2_table <- data.frame(
  response = c("Gene expression PC1", "PIabs"),
  R2_mean  = round(c(r2_pc1[1,  "Estimate"],
                      r2_piabs[1, "Estimate"]), 3),
  R2_lower = round(c(r2_pc1[1,  "Q2.5"],
                      r2_piabs[1, "Q2.5"]), 3),
  R2_upper = round(c(r2_pc1[1,  "Q97.5"],
                      r2_piabs[1, "Q97.5"]), 3)
)

message("\nBayesian R² per sub-model:")
print(r2_table)

write.csv(r2_table, "sem_r2_no_fvfm.csv", row.names = FALSE)
message("Saved: sem_r2_no_fvfm.csv")

# -----------------------------------------------------------------------------
# 8. Conditional effects plots
# -----------------------------------------------------------------------------
message("\n--- Step 8: Conditional effects plots ---")

pdf("sem_conditional_effects_pc1.pdf", width = 10, height = 5)
plot(conditional_effects(fit_sem, resp = "pc1std"), ask = FALSE)
dev.off()

pdf("sem_conditional_effects_piabs.pdf", width = 10, height = 5)
plot(conditional_effects(fit_sem, resp = "meanpiabs"), ask = FALSE)
dev.off()

message("Saved: sem_conditional_effects_pc1.pdf")
message("Saved: sem_conditional_effects_piabs.pdf")

# -----------------------------------------------------------------------------
# 9. Path diagram
# -----------------------------------------------------------------------------
message("\n--- Step 9: Path diagram ---")

coef_full <- as.data.frame(fixef(fit_sem))
coef_full$parameter <- rownames(coef_full)

edges_raw <- data.frame(
  from_name = c(
    "Leaf\nposition",           # pos → pc1
    "Lux",                      # lux → pc1
    "Lux",                      # lux → piabs
    "Gene expression\n(PC1)"    # pc1 → piabs
  ),
  to_name = c(
    "Gene expression\n(PC1)",   # pos → pc1
    "Gene expression\n(PC1)",   # lux → pc1
    "PIabs",                    # lux → piabs
    "PIabs"                     # pc1 → piabs
  ),
  param = c(
    "pc1std_mopos",
    "pc1std_lux_std",
    "meanpiabs_lux_std",
    "meanpiabs_pc1_std"
  ),
  stringsAsFactors = FALSE
)

edges_raw <- merge(
  edges_raw,
  coef_full[, c("parameter", "Estimate", "Q2.5", "Q97.5")],
  by.x = "param", by.y = "parameter",
  all.x = TRUE
)

edges_raw$direction <- edges_raw$Estimate > 0
edges_raw$abs_coef  <- abs(edges_raw$Estimate)
edges_raw$label     <- paste0(
  round(edges_raw$Estimate, 2),
  "\n[", round(edges_raw$Q2.5, 2),
  ", ", round(edges_raw$Q97.5, 2), "]"
)

# Node positions
nodes <- data.frame(
  name = c("Leaf\nposition",
           "Lux",
           "Gene expression\n(PC1)",
           "PIabs"),
  x    = c(1, 3, 5, 7),
  y    = c(3, 4, 3, 4),
  stringsAsFactors = FALSE
)

from_coords        <- nodes; names(from_coords) <- c("from_name", "x_from", "y_from")
to_coords          <- nodes; names(to_coords)   <- c("to_name",   "x_to",   "y_to")
edges <- merge(edges_raw, from_coords, by = "from_name", all.x = TRUE)
edges <- merge(edges,     to_coords,   by = "to_name",   all.x = TRUE)

# Label nudges to avoid overlap
edges$label_x <- (edges$x_from + edges$x_to) / 2
edges$label_y <- (edges$y_from + edges$y_to) / 2 + ifelse(
  edges$from_name == "Leaf\nposition" &
    edges$to_name == "Gene expression\n(PC1)",   0.15,
  ifelse(edges$from_name == "Lux" &
           edges$to_name == "Gene expression\n(PC1)", -0.15,
  ifelse(edges$from_name == "Lux" &
           edges$to_name == "PIabs",                   0.15,
  ifelse(edges$from_name == "Gene expression\n(PC1)" &
           edges$to_name == "PIabs",                  -0.15,
  0))))

p_sem <- ggplot() +
  geom_segment(
    data = edges,
    aes(x = x_from, y = y_from, xend = x_to, yend = y_to,
        colour = direction, linewidth = abs_coef),
    arrow = arrow(length = unit(0.3, "cm"), type = "closed")
  ) +
  geom_label(
    data = edges,
    aes(x = label_x, y = label_y, label = label),
    size = 2.8, fill = "white", colour = "#2C2C2A",
    label.size = 0.2, label.padding = unit(0.15, "lines")
  ) +
  geom_tile(
    data = nodes, aes(x = x, y = y),
    width = 1.6, height = 0.55,
    fill = "white", colour = "#444441", linewidth = 0.6
  ) +
  geom_text(
    data = nodes, aes(x = x, y = y, label = name),
    size = 3.2, fontface = "bold", colour = "#2C2C2A", lineheight = 0.9
  ) +
  scale_colour_manual(
    values = c("TRUE" = "#1D9E75", "FALSE" = "#D85A30"),
    labels = c("TRUE" = "Positive effect", "FALSE" = "Negative effect"),
    name   = NULL
  ) +
  scale_linewidth_continuous(range = c(0.5, 2.5), guide = "none") +
  xlim(-0.2, 8.5) + ylim(1.5, 5) +
  labs(
    title    = "Bayesian SEM — light environment, gene expression and PIabs",
    subtitle = "Posterior median | 95% credible interval | All paths credible (CI excludes zero)"
  ) +
  theme_void(base_size = 12) +
  theme(
    legend.position = "bottom",
    plot.title    = element_text(face = "bold", size = 12, margin = margin(b = 4)),
    plot.subtitle = element_text(size = 9, colour = "grey40", margin = margin(b = 8)),
    plot.margin   = margin(10, 10, 10, 10)
  )

ggsave("sem_path_diagram_no_fvfm.pdf", p_sem, width = 10, height = 6)
message("Saved: sem_path_diagram_no_fvfm.pdf")

# -----------------------------------------------------------------------------
# 10. Summary
# -----------------------------------------------------------------------------
message("\n============================================================")
message("SEM complete. Output files:")
message("  sem_bayesian_fit_no_fvfm          — saved brms fit object")
message("  sem_trace_plots_no_fvfm.pdf       — MCMC convergence")
message("  sem_path_coefficients_no_fvfm.csv — path coefficient table")
message("  sem_r2_no_fvfm.csv               — Bayesian R² per sub-model")
message("  sem_conditional_effects_pc1.pdf   — conditional effects PC1")
message("  sem_conditional_effects_piabs.pdf — conditional effects PIabs")
message("  sem_path_diagram_no_fvfm.pdf      — path diagram")
message("============================================================")
